name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: "ramsey/composer-install@v2"
      with:
        working-directory: "client"
    - uses: php-actions/phpunit@v3
      env:
        CLIENT_KEY: 04ee84bc7f8df421fe0c10ae679bb43f
      with:
        configuration: ./client/tests/phpunit.xml
